version: '3.9'
services:
  server:
    image: nginx:1.25-alpine
    container_name: test_server
    environment:
      NGINX_PORT: 80
      NGINX_ROOT: /var/www/default/web
      NGINX_FAST_CGI_PASS: test_app:9000
    volumes:
      - './default.conf.template:/etc/nginx/templates/default.conf.template'
      - './public:/var/www/default/public'
    networks:
      - local
    depends_on:
      - app
    ports:
      - '${NGINX_EXTERNAL_PORT}:80'
  db:
    image: postgres:15-alpine
    container_name: test_db
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
    networks:
      - local
    ports:
      - '${DB_EXTERNAL_PORT}:5432'
  app:
    build:
      context: .
      args:
        - 'xdebug=${XDEBUG:-false}'
    container_name: test_app
    working_dir: '/var/www/default'
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT} idekey=PHPSTORM log_level=0
      XDEBUG_MODE: debug
    volumes:
      - '.:/var/www/default'
    privileged: true
    depends_on:
      - db
    networks:
      - local
    restart: on-failure
  composer:
    image: composer:2.6
    volumes:
      - .:/app
    command: i
  redis:
    image: 'redis:latest'
    container_name: test_redis
    networks:
      - local
networks:
  local:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
